name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUST_DIR: rust-solver/
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache Rust Dependencies
      id: cache-rust-deps-test
      uses: actions/cache@v4
      env: 
        cache-name: "rust dependencies"
      with:
        path: |
          ${{env.RUST_DIR}}/target/debug/.fingerprint
          ${{env.RUST_DIR}}/target/debug/build
          ${{env.RUST_DIR}}/target/debug/deps
        key: ${{ runner.os }}-build-rust-test
    - name: Build
      working-directory: ${{env.RUST_DIR}}
      run: cargo build --verbose
    - name: Run tests
      working-directory: ${{env.RUST_DIR}}
      run: cargo test --verbose
